on:
  push:
    branches:
      - main

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Kscript
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin 1.6.21
          sdk install kscript 4.0.3
          echo $PATH >> $GITHUB_PATH

      - name: Set Version
        working-directory: scripts
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          VERSION=$(kscript get_version.kts "$COMMIT_MESSAGE")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Print Version
        run: echo ${{ env.$VERSION }}
